language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - 454799532@qq.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install --save gitbook-plugin-todo
  - npm install -g gitbook-cli
  - gitbook install
  - gitbook serve

script:
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

branches:
  only:
    - main  #设置git分支名

env:
  global:
    - REF=github.com/diyiyao/mybook.git # 设置 github 地址
